baseURL = "https://anilzen.github.io/adaptive_regression/"
title = "Adaptive Regression"
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = false

[params]
  geekdocToC = 3
  geekdocRepo = "https://github.com/anilzen/adaptive_regression/"
  geekdocEditPath = "edit/docs/content/"
  geekdocSearchShowParent = true
  geekdocLogo = "logo.png"